'use strict';
window.HeartsText = (() => {
  const en = {
    title:'Hearts',you:'You',menu:'Menu',help:'How to play',close:'Close',back:'Back to the game',settings:'Settings',newGame:'New game',restartTitle:'Start a new game?',restartText:'Your current game will be replaced.',keepPlaying:'Keep playing',start:'Start a new game',
    totalScores:'Total scores · lowest wins',handPoints:'This hand: you have {n} points.',lastTrick:'Last trick',saveNote:'Your progress is saved automatically.',savedProblem:'Progress could not be saved. Keep this tab open.',recovered:'Your game was recovered from the previous save.',damaged:'The saved game could not be restored. A new game is ready.',
    choose3:'Choose 3 cards',ready:'Ready to pass',passLeft:'Pass left',passRight:'Pass right',passAcross:'Pass across',passTo:'Pass {direction} to {name}',left:'left',right:'right',across:'across',hold:'No passing this hand',count3:'{n} of 3',limit3:'Three cards chosen. Put one back before choosing another.',received:'Your new cards',receivedFrom:'3 cards received from {name}',newLabel:'NEW',continue:'Continue',begin:'Start playing',yourTurn:'Your turn',turn:'{name}’s turn',chooseCard:'Choose a card',chooseSuit:'Choose {suit}',leadTwo:'Play the 2 of clubs',follow:'Your turn · follow {suit}',playCard:'Play card',choose1:'Choose 1',wait:'Please wait',nextTrick:'Next trick',seeScores:'See scores',cardPlayed:'Trick complete',trickWon:'{name} took the trick · {n} points',yourTrick:'You took the trick · {n} points',chooseLegal:'Choose a highlighted card that follows the rules.',selected:'{card} selected. Press Play card to confirm.',
    clubs:'clubs',diamonds:'diamonds',spades:'spades',hearts:'hearts',ace:'Ace',jack:'Jack',queen:'Queen',king:'King',cardName:'{rank} of {suit}',handNumber:'Hand {n}',points:'{n} points',player:'Player',thisHand:'This hand',total:'Total',handComplete:'Hand complete',lowest:'Lowest total wins.',youWon:'You won!',won:'{name} won',lowestScore:'{n} points · lowest total',moon:'{name} shot the moon',moonDetail:'All 13 hearts and the queen of spades went to one player. Everyone else adds 26 points.',endReason:'A player reached 100 points. The lowest total wins.',tie:'Lowest scores tied. Play another hand.',nextPass:'Next hand: pass {direction}.',nextHold:'Next hand: keep your cards.',playAgain:'Play again',reviewTrick:'Review last trick',tookTrick:'{name} took this trick.',youTookTrick:'You took this trick.',led:'{name} led {suit}.',noPoints:'No hearts or queen of spades.',queenPoints:'Queen of spades: 13',heartPoints:'Hearts: {n}',
    language:'Language',pace:'Computer speed',slow:'Gentle',normal:'Normal',fast:'Quick',sound:'Soft card sounds',on:'On',off:'Off',installTitle:'Play offline',installText:'On iPhone, open this page in Safari. Tap Share, then Add to Home Screen. Open the game once online before playing offline.',
    ruleGoal:'Keep your total low. Each heart is 1 point; the queen of spades is 13. When someone reaches 100, the lowest total wins. A tie for lowest continues for another hand.',
    rulePass:'Choose three cards, then confirm the pass. Passing goes left, right, across, then no passing. Review the cards you receive before continuing.',
    rulePlay:'The 2 of clubs starts each hand. Follow the suit that was led if you can. Otherwise, play any legal card. On the first trick, you must avoid hearts and the queen of spades if another card is available.',
    ruleHearts:'You can lead hearts after a heart has been played, or when you have only hearts. The queen of spades does not break hearts. The highest card of the led suit takes the trick.',
    ruleMoon:'Take all 13 hearts and the queen of spades to shoot the moon. You add zero points; each other player adds 26.',
    ruleControls:'Cards without shading can be played. Shaded cards must wait. Tap an unshaded card, then press Play card. A sole legal card is selected immediately and plays after three seconds. Tap Play card to play sooner. The cards move into the winner’s pile. The next trick starts as soon as the cards reach the winner’s pile. Menu pauses automatic play. Menu includes the last trick and settings. In Settings, you can turn on one-tap play; it is off by default.'
  };
  const es = {
    title:'Corazones',you:'Tú',menu:'Menú',help:'Cómo jugar',close:'Cerrar',back:'Volver al juego',settings:'Ajustes',newGame:'Nueva partida',restartTitle:'¿Nueva partida?',restartText:'Se reemplazará la partida actual.',keepPlaying:'Seguir jugando',start:'Nueva partida',totalScores:'Puntos totales · gana el menor',handPoints:'Esta mano: tienes {n} puntos.',lastTrick:'Última baza',saveNote:'Tu progreso se guarda automáticamente.',savedProblem:'No se pudo guardar. Mantén abierta esta pestaña.',recovered:'Se recuperó la partida anterior.',damaged:'No se pudo recuperar la partida. Hay una nueva lista.',
    choose3:'Elige 3 cartas',ready:'Listas para pasar',passLeft:'Pasar izquierda',passRight:'Pasar derecha',passAcross:'Pasar enfrente',passTo:'Pasa a {name} · {direction}',left:'izquierda',right:'derecha',across:'enfrente',hold:'Esta mano no se pasan cartas',count3:'{n} de 3',limit3:'Ya elegiste tres. Quita una antes de elegir otra.',received:'Cartas recibidas',receivedFrom:'3 cartas de {name}',newLabel:'NUEVA',continue:'Continuar',begin:'Empezar',yourTurn:'Tu turno',turn:'Turno de {name}',chooseCard:'Elige una carta',chooseSuit:'Elige {suit}',leadTwo:'Juega el 2 de tréboles',follow:'Tu turno · {suit}',playCard:'Jugar carta',choose1:'Elige 1',wait:'Espera',nextTrick:'Siguiente baza',seeScores:'Ver puntos',cardPlayed:'Baza terminada',trickWon:'{name} ganó · {n} puntos',yourTrick:'Ganaste la baza · {n} puntos',chooseLegal:'Elige una carta permitida por las reglas.',selected:'{card}. Pulsa Jugar carta para confirmar.',
    clubs:'tréboles',diamonds:'diamantes',spades:'picas',hearts:'corazones',ace:'As',jack:'Jota',queen:'Reina',king:'Rey',cardName:'{rank} de {suit}',handNumber:'Mano {n}',points:'{n} puntos',player:'Jugador',thisHand:'Esta mano',total:'Total',handComplete:'Mano terminada',lowest:'Gana el total más bajo.',youWon:'¡Ganaste!',won:'Ganó {name}',lowestScore:'{n} puntos · el menor total',moon:'{name} hizo pleno',moonDetail:'Un jugador tomó todos los corazones y la reina de picas. Los demás suman 26 puntos.',endReason:'Alguien llegó a 100 puntos. Gana el total más bajo.',tie:'Empate en el menor total. Juega otra mano.',nextPass:'Próxima mano: pasar {direction}.',nextHold:'Próxima mano: conserva tus cartas.',playAgain:'Jugar de nuevo',reviewTrick:'Ver última baza',tookTrick:'{name} ganó esta baza.',youTookTrick:'Ganaste esta baza.',led:'{name} salió con {suit}.',noPoints:'Sin corazones ni reina de picas.',queenPoints:'Reina de picas: 13',heartPoints:'Corazones: {n}',
    language:'Idioma',pace:'Velocidad de rivales',slow:'Tranquila',normal:'Normal',fast:'Rápida',sound:'Sonidos suaves',on:'Sí',off:'No',installTitle:'Jugar sin conexión',installText:'En iPhone, abre la página en Safari. Pulsa Compartir y Añadir a pantalla de inicio. Abre el juego una vez con conexión antes de jugar sin internet.',ruleGoal:'Mantén bajo tu total. Cada corazón vale 1 punto; la reina de picas, 13. Al llegar alguien a 100, gana el menor total. Si hay empate en el menor total, se juega otra mano.',rulePass:'Elige tres cartas y confirma. Se pasan a la izquierda, a la derecha, enfrente y luego no se pasan. Revisa las cartas recibidas antes de continuar.',rulePlay:'Empieza el 2 de tréboles. Sigue el palo de salida si puedes; si no, juega una carta permitida. En la primera baza, evita corazones y la reina de picas si tienes otra carta.',ruleHearts:'Puedes salir con corazones después de que se haya jugado uno, o si solo tienes corazones. La reina de picas no los habilita. Gana la carta más alta del palo de salida.',ruleMoon:'Tomar todos los corazones y la reina de picas es hacer pleno: tú sumas cero y los demás suman 26.',ruleControls:'Puedes jugar las cartas sin sombrear. Las sombreadas deben esperar. Toca una carta sin sombrear y confirma con Jugar carta. Si solo hay una válida, se selecciona y se juega tras tres segundos. Pulsa Jugar carta para jugar antes. Las cartas van al montón de quien ganó. La siguiente baza empieza cuando las cartas llegan al montón. Menú pausa el juego automático. El Menú incluye la última baza y los ajustes. Puedes activar el juego con un toque en Ajustes; está desactivado de forma predeterminada.'
  };
  const vi = {
    title:'Hearts',you:'Bạn',menu:'Menu',help:'Cách chơi',close:'Đóng',back:'Trở lại bàn',settings:'Cài đặt',newGame:'Ván mới',restartTitle:'Bắt đầu ván mới?',restartText:'Ván hiện tại sẽ được thay thế.',keepPlaying:'Chơi tiếp',start:'Bắt đầu ván mới',totalScores:'Tổng điểm · ít nhất thắng',handPoints:'Lượt này: bạn có {n} điểm.',lastTrick:'Lượt đánh trước',saveNote:'Tiến trình được lưu tự động.',savedProblem:'Không lưu được. Hãy giữ thẻ này mở.',recovered:'Đã khôi phục bản lưu trước.',damaged:'Không khôi phục được ván đã lưu. Đã chia ván mới.',
    choose3:'Chọn 3 lá',ready:'Sẵn sàng chuyển',passLeft:'Chuyển trái',passRight:'Chuyển phải',passAcross:'Chuyển đối diện',passTo:'Chuyển cho {name} · {direction}',left:'trái',right:'phải',across:'đối diện',hold:'Lượt này không chuyển bài',count3:'{n} trên 3',limit3:'Đã chọn ba lá. Bỏ chọn một lá trước khi chọn lá khác.',received:'Bài vừa nhận',receivedFrom:'Nhận 3 lá từ {name}',newLabel:'MỚI',continue:'Tiếp tục',begin:'Bắt đầu chơi',yourTurn:'Đến lượt bạn',turn:'Lượt của {name}',chooseCard:'Chọn một lá',chooseSuit:'Chọn lá {suit}',leadTwo:'Đánh lá 2 tép',follow:'Lượt bạn · theo {suit}',playCard:'Đánh bài',choose1:'Chọn 1 lá',wait:'Vui lòng chờ',nextTrick:'Lượt tiếp',seeScores:'Xem điểm',cardPlayed:'Xong lượt đánh',trickWon:'{name} ăn bài · {n} điểm',yourTrick:'Bạn ăn bài · {n} điểm',chooseLegal:'Chọn một lá được phép đánh.',selected:'Đã chọn {card}. Nhấn Đánh bài để xác nhận.',
    clubs:'tép',diamonds:'rô',spades:'bích',hearts:'cơ',ace:'Át',jack:'J',queen:'Q',king:'K',cardName:'{rank} {suit}',handNumber:'Lượt chia {n}',points:'{n} điểm',player:'Người chơi',thisHand:'Lượt này',total:'Tổng',handComplete:'Xong lượt chia',lowest:'Tổng điểm ít nhất thắng.',youWon:'Bạn thắng!',won:'{name} thắng',lowestScore:'{n} điểm · tổng thấp nhất',moon:'{name} ăn trọn điểm',moonDetail:'Một người ăn đủ 13 lá cơ và Q bích. Mỗi người còn lại cộng 26 điểm.',endReason:'Có người đạt 100 điểm. Tổng điểm thấp nhất thắng.',tie:'Đồng hạng thấp nhất. Chơi thêm một lượt chia.',nextPass:'Lượt sau: chuyển {direction}.',nextHold:'Lượt sau: giữ nguyên bài.',playAgain:'Chơi lại',reviewTrick:'Xem lượt đánh trước',tookTrick:'{name} ăn lượt bài này.',youTookTrick:'Bạn ăn lượt bài này.',led:'{name} đi {suit} trước.',noPoints:'Không có lá cơ hay Q bích.',queenPoints:'Q bích: 13',heartPoints:'Lá cơ: {n}',
    language:'Ngôn ngữ',pace:'Tốc độ đối thủ',slow:'Chậm',normal:'Vừa',fast:'Nhanh',sound:'Âm thanh nhẹ',on:'Bật',off:'Tắt',installTitle:'Chơi ngoại tuyến',installText:'Trên iPhone, mở trang bằng Safari. Nhấn Chia sẻ rồi Thêm vào Màn hình chính. Mở trò chơi một lần khi có mạng trước khi chơi ngoại tuyến.',ruleGoal:'Giữ tổng điểm thấp. Mỗi lá cơ là 1 điểm; Q bích là 13. Khi có người đạt 100 điểm, tổng thấp nhất thắng. Nếu đồng hạng thấp nhất, chơi thêm một lượt chia.',rulePass:'Chọn ba lá rồi xác nhận. Chuyển trái, phải, đối diện, rồi không chuyển. Xem các lá vừa nhận trước khi tiếp tục.',rulePlay:'Lá 2 tép mở đầu. Phải theo chất được đánh trước nếu có. Nếu không, đánh lá hợp lệ khác. Trong lượt đánh đầu, tránh cơ và Q bích nếu còn lá khác.',ruleHearts:'Chỉ được đi cơ trước sau khi đã có lá cơ được đánh, hoặc khi chỉ còn cơ. Q bích không mở cơ. Lá cao nhất của chất đi trước ăn bài.',ruleMoon:'Ăn đủ 13 lá cơ và Q bích thì bạn cộng 0 điểm, mỗi người còn lại cộng 26.',ruleControls:'Được đánh lá không bị làm tối. Lá bị làm tối phải chờ. Chạm lá không bị làm tối rồi nhấn Đánh bài. Nếu chỉ có một lá hợp lệ, lá đó được chọn ngay và tự đánh sau ba giây. Nhấn Đánh bài để đi sớm hơn. Các lá bài chuyển về chồng bài của người thắng. Lượt tiếp bắt đầu ngay khi bài về chồng bài của người thắng. Menu tạm dừng tự động chơi. Menu có lượt đánh trước và cài đặt. Có thể bật chạm một lần để đánh bài trong Cài đặt; mặc định tắt.'
  };
  Object.assign(en,{"handShort":"hand","seatSummary":"{name}: {hand} points this hand, {total} total, {hearts} hearts. {queen}","queenTaken":"Q♠ taken","queenStillOut":"Q♠ still out","moonWatch":"Moon watch · {name}","moonWarning":"Moon alert · {name}","moonProgress":"{n}/13 hearts · {queen}","pointReminder":"Each heart: 1 point · Q♠: 13","handProgress":"Trick {n}/13 · {points} points left","moonBlocked":"Points split · no moon this hand","heartsOpen":"Hearts are open to lead.","heartsClosed":"Hearts must be broken before leading.","playableCount":"{n} playable","followSuit":"Follow {suit}","yourChoice":"Your choice","firstTrick":"First trick","leadSuit":"Lead another suit","onlyCard":"Only choice. Plays automatically.","confirmCard":"Press Play card, or choose another.","brightCards":"Play a card without shading.","passHint":"Choose three, then confirm the pass.","receivedHint":"Gold outlines mark your new cards.","holdHint":"Keep your cards. No passing this hand.","readyWhenYouAre":"Continue when you are ready.","collectingHint":"The cards are going to the winner.","yourTurnSoon":"Your turn is coming.","firstNoPoints":"Save hearts and Q♠ on the first trick.","mustFollow":"You must follow {suit}.","cleanTrick":"Clean trick · no points added","trickPoints":"{n} points on the table","cleanHand":"A clean hand!","cleanHandDetail":"No points added. Nicely played."});
  Object.assign(es,{"handShort":"mano","seatSummary":"{name}: {hand} puntos esta mano, {total} en total, {hearts} corazones. {queen}","queenTaken":"Q♠ tomada","queenStillOut":"Q♠ en juego","moonWatch":"Posible pleno · {name}","moonWarning":"Alerta de pleno · {name}","moonProgress":"{n}/13 corazones · {queen}","pointReminder":"Cada corazón: 1 punto · Q♠: 13","handProgress":"Baza {n}/13 · quedan {points} puntos","moonBlocked":"Puntos repartidos · ya no hay pleno","heartsOpen":"Ya puedes salir con corazones.","heartsClosed":"Aún no puedes salir con corazones.","playableCount":"{n} válidas","followSuit":"Sigue {suit}","yourChoice":"Tú eliges","firstTrick":"Primera baza","leadSuit":"Sal con otro palo","onlyCard":"Única opción. Se juega sola.","confirmCard":"Pulsa Jugar carta o elige otra.","brightCards":"Juega una carta sin sombrear.","passHint":"Elige tres y confirma el pase.","receivedHint":"El borde dorado marca las nuevas.","holdHint":"Conserva tus cartas. No hay pase.","readyWhenYouAre":"Continúa cuando estés lista.","collectingHint":"Las cartas van a quien ganó.","yourTurnSoon":"Tu turno está por llegar.","firstNoPoints":"Reserva corazones y Q♠ en esta baza.","mustFollow":"Debes seguir {suit}.","cleanTrick":"Baza limpia · sin puntos","trickPoints":"{n} puntos en la mesa","cleanHand":"¡Mano sin puntos!","cleanHandDetail":"No sumaste puntos. Bien jugado."});
  Object.assign(vi,{"handShort":"lượt","seatSummary":"{name}: {hand} điểm lượt này, tổng {total}, {hearts} lá cơ. {queen}","queenTaken":"Đã ăn Q♠","queenStillOut":"Q♠ chưa có chủ","moonWatch":"Cơ hội ăn trọn · {name}","moonWarning":"Chú ý ăn trọn · {name}","moonProgress":"{n}/13 lá cơ · {queen}","pointReminder":"Mỗi lá cơ: 1 điểm · Q♠: 13","handProgress":"Lượt {n}/13 · còn {points} điểm","moonBlocked":"Điểm đã chia · không thể ăn trọn","heartsOpen":"Đã được phép đi cơ trước.","heartsClosed":"Chưa được phép đi cơ trước.","playableCount":"{n} lá hợp lệ","followSuit":"Theo chất {suit}","yourChoice":"Bạn chọn bài","firstTrick":"Lượt đánh đầu","leadSuit":"Đi chất khác trước","onlyCard":"Chỉ một lá. Tự động đánh.","confirmCard":"Nhấn Đánh bài hoặc chọn lá khác.","brightCards":"Đánh lá không bị làm tối.","passHint":"Chọn ba lá rồi xác nhận chuyển.","receivedHint":"Viền vàng đánh dấu bài vừa nhận.","holdHint":"Giữ bài. Lượt này không chuyển.","readyWhenYouAre":"Chơi tiếp khi bạn sẵn sàng.","collectingHint":"Bài đang về người thắng lượt này.","yourTurnSoon":"Sắp đến lượt bạn.","firstNoPoints":"Giữ lại cơ và Q♠ ở lượt đánh đầu.","mustFollow":"Bạn phải theo chất {suit}.","cleanTrick":"Lượt sạch · không thêm điểm","trickPoints":"{n} điểm trên bàn","cleanHand":"Không thêm điểm!","cleanHandDetail":"Bạn không bị thêm điểm. Chơi tốt!"});
  Object.assign(en,{chooseAny:'Choose any card.',chooseLegal:'Choose a card that follows the rules.'});
  Object.assign(es,{chooseAny:'Elige cualquier carta.'});
  Object.assign(vi,{chooseAny:'Chọn bất kỳ lá nào.'});
  Object.assign(en,{receivedHint:'Only the new cards are bright.',receivingHint:'Watch your new cards join your hand.',passedYou:'{name} passed you these',cardsAdded:'Added to your hand',newCardName:'New card: {card}'});
  Object.assign(es,{receivedHint:'Solo las nuevas están sin sombrear.',receivingHint:'Mira cómo llegan tus cartas nuevas.',passedYou:'{name} te pasó estas cartas',cardsAdded:'Añadidas a tu mano',newCardName:'Carta nueva: {card}'});
  Object.assign(vi,{receivedHint:'Chỉ các lá mới được giữ sáng.',receivingHint:'Xem bài mới về tay bạn.',passedYou:'{name} chuyển cho bạn',cardsAdded:'Đã thêm vào bài của bạn',newCardName:'Lá mới: {card}'});
  Object.assign(en,{autoSeconds:'{n}s',autoContinueHint:'Continuing automatically. Menu pauses.'});
  Object.assign(es,{autoSeconds:'{n}s',autoContinueHint:'Sigue solo. Menú pausa.'});
  Object.assign(vi,{autoSeconds:'{n}s',autoContinueHint:'Tự tiếp tục. Menu để tạm dừng.'});
  Object.assign(en,{heartsTaken:'Hearts taken this hand',ownershipSummary:'{name}: {n} hearts. {queen}',yourMoonChance:'You could shoot the moon',theirMoonChance:'{name} could shoot the moon',youShotMoon:'You shot the moon',stopWithQueen:'Q♠ won by anyone else stops it.',stopTheirMoon:'A heart won by anyone else stops it.',takeAllPoints:'Take every heart and Q♠.',othersGet26:'Each opponent gets 26 points.',youGet26:'You and the others get 26 points.',noMoon:'No one can shoot the moon',pointsSplit:'Points are split between players.',noPointsTaken:'No hearts taken yet',allPointsOut:'All 13 hearts and Q♠ are still out.'});
  Object.assign(es,{heartsTaken:'Corazones tomados en esta mano',ownershipSummary:'{name}: {n} corazones. {queen}',yourMoonChance:'Puedes hacer pleno',theirMoonChance:'{name} puede hacer pleno',youShotMoon:'Hiciste pleno',stopWithQueen:'Q♠ para otro impide el pleno.',stopTheirMoon:'Un corazón para otro impide el pleno.',takeAllPoints:'Toma todos los corazones y Q♠.',othersGet26:'Cada rival suma 26 puntos.',youGet26:'Tú y los demás suman 26 puntos.',noMoon:'Nadie puede hacer pleno',pointsSplit:'Los puntos están repartidos.',noPointsTaken:'Nadie tomó corazones aún',allPointsOut:'Los 13 corazones y Q♠ siguen en juego.'});
  Object.assign(vi,{heartsTaken:'Lá cơ đã ăn trong lượt này',ownershipSummary:'{name}: {n} lá cơ. {queen}',yourMoonChance:'Bạn có thể ăn trọn điểm',theirMoonChance:'{name} có thể ăn trọn điểm',youShotMoon:'Bạn đã ăn trọn điểm',stopWithQueen:'Người khác ăn Q♠ là chặn được.',stopTheirMoon:'Người khác ăn một lá cơ là chặn được.',takeAllPoints:'Ăn mọi lá cơ và Q♠.',othersGet26:'Mỗi đối thủ cộng 26 điểm.',youGet26:'Bạn và người khác cộng 26 điểm.',noMoon:'Không ai có thể ăn trọn điểm',pointsSplit:'Điểm đã chia cho nhiều người.',noPointsTaken:'Chưa ai ăn lá cơ',allPointsOut:'Cả 13 lá cơ và Q♠ đều chưa có chủ.'});
  Object.assign(en,{tapToPlay:'Play cards with one tap',tapACard:'Tap a card',tapAny:'Tap any card to play it.',tapFollow:'Tap {suit} to play.',tapPlayable:'Tap an unshaded card to play it.'});
  Object.assign(es,{tapToPlay:'Jugar cartas con un toque',tapACard:'Toca una carta',tapAny:'Toca cualquier carta para jugar.',tapFollow:'Toca {suit} para jugar.',tapPlayable:'Toca una carta sin sombrear.'});
  Object.assign(vi,{tapToPlay:'Chạm một lần để đánh bài',tapACard:'Chạm một lá',tapAny:'Chạm lá bất kỳ để đánh.',tapFollow:'Chạm lá {suit} để đánh.',tapPlayable:'Chạm lá không bị làm tối để đánh.'});
  Object.assign(en,{
    opponentNames:'Opponent names',namesInvitation:'Give your opponents names you choose. To unlock this option, promise to donate to a school.',
    schoolChoice:'Consider a school in your neighborhood, or choose any school you like. The amount is up to you; donate directly to the school.',
    schoolTrust:'We trust you to follow through. Your promise unlocks opponent names right away.',schoolPromise:'I promise to donate to a school',notNow:'Not now',
    namesThanks:'Thank you for your promise. Change names any time.',
    namesHint:'Up to 10 characters per name. Leave blank to use the original.',
    opponentLeft:'Left opponent',opponentMiddle:'Middle opponent',opponentRight:'Right opponent',resetNames:'Use original names',saveNames:'Save names',cancelNames:'Cancel changes',namesSaved:'Opponent names saved.',
    namesStorageProblem:'Your names and promise work for now, but could not be saved. Keep this tab open.'
  });
  Object.assign(es,{
    opponentNames:'Nombres de rivales',namesInvitation:'Elige los nombres de tus rivales. Para activar esta opción, promete hacer una donación a una escuela.',
    schoolChoice:'Puede ser una escuela de tu barrio o cualquier otra que elijas. Tú decides cuánto donar; haz la donación directamente a la escuela.',
    schoolTrust:'Confiamos en que cumplirás tu promesa. Con ella puedes cambiar los nombres de inmediato.',schoolPromise:'Prometo donar a una escuela',notNow:'Ahora no',
    namesThanks:'Gracias por tu promesa. Cambia los nombres cuando quieras.',
    namesHint:'Hasta 10 caracteres por nombre. Déjalo en blanco para usar el original.',
    opponentLeft:'Rival de la izquierda',opponentMiddle:'Rival del centro',opponentRight:'Rival de la derecha',resetNames:'Usar nombres originales',saveNames:'Guardar nombres',cancelNames:'Cancelar cambios',namesSaved:'Nombres guardados.',
    namesStorageProblem:'Tus nombres y tu promesa funcionan por ahora, pero no se pudieron guardar. Mantén abierta esta pestaña.'
  });
  Object.assign(vi,{
    opponentNames:'Tên đối thủ',namesInvitation:'Đặt tên cho các đối thủ theo ý bạn. Để mở tùy chọn này, hãy hứa quyên góp cho một trường học.',
    schoolChoice:'Bạn có thể chọn một trường gần nhà hoặc bất kỳ trường nào bạn muốn. Số tiền tùy bạn; hãy quyên góp trực tiếp cho trường.',
    schoolTrust:'Chúng tôi tin bạn sẽ giữ lời. Chỉ cần hứa là bạn có thể đổi tên đối thủ ngay.',schoolPromise:'Tôi hứa quyên góp cho một trường',notNow:'Để sau',
    namesThanks:'Cảm ơn lời hứa của bạn. Bạn có thể đổi tên bất cứ lúc nào.',
    namesHint:'Tối đa 10 ký tự mỗi tên. Để trống để dùng tên ban đầu.',
    opponentLeft:'Đối thủ bên trái',opponentMiddle:'Đối thủ ở giữa',opponentRight:'Đối thủ bên phải',resetNames:'Dùng tên ban đầu',saveNames:'Lưu tên',cancelNames:'Hủy thay đổi',namesSaved:'Đã lưu tên đối thủ.',
    namesStorageProblem:'Tên và lời hứa của bạn có hiệu lực lúc này nhưng chưa lưu được. Hãy giữ thẻ này mở.'
  });
  const languages = {en,es,vi};
  let language = 'en';
  function set(value) { language = Object.hasOwn(languages,value) ? value : 'en'; document.documentElement.lang = language; }
  function t(key, values = {}) { return (languages[language][key] || en[key] || key).replace(/\{(\w+)\}/g,(_,name)=>String(values[name] ?? '')); }
  return {set,t,keys:Object.keys(en),languages};
})();
