"""Rebuild the received-card previews from the current local Hearts app."""
from pathlib import Path
import json

here = Path(__file__).resolve().parent
source = here.parent.parent / 'hearts'
app = (source / 'app.js').read_text()
storage = "const KEY = 'codex-hearts-game-v2', BACKUP = KEY + '-backup', PREFS = 'codex-hearts-settings-v2';"
assert app.count(storage) == 1, 'Stop: the save namespace must be isolated before building a preview.'
app = app.replace(storage, "const KEY = 'codex-hearts-received-option-' + document.documentElement.dataset.receiptVariant, BACKUP = KEY + '-backup', PREFS = KEY + '-settings';")
fixture = json.loads((here / 'fixture.json').read_text())
seed = """  // Only this practice hand is reset; real game saves are never accessed.
  localStorage.removeItem(BACKUP);
  localStorage.setItem(KEY,JSON.stringify({version:2,game:%s,selected:[]}));
  localStorage.setItem(PREFS,JSON.stringify({language:'en',pace:'slow',sound:false}));
""" % json.dumps(fixture)
app = app.replace('  const params =', seed + '  const params =')
app = app.replace("    $('language').value = preferences.language;", "    ReceivedPreview.render(game);\n    $('language').value = preferences.language;")
app = app.replace("  if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('service-worker.js').catch(()=>{});", '')
assert 'codex-hearts-game-v2' not in app and 'serviceWorker.register' not in app
(here / 'demo-app.js').write_text('// Generated by build-preview.py.\n' + app)
html = (source / 'index.html').read_text()
for asset in ('style.css', 'screens.css', 'game.css', 'deck.js', 'engine.js', 'insights.js', 'i18n.js', 'icons/icon-180.png'):
    html = html.replace('"' + asset, '"../../hearts/' + asset)
html = html.replace('  <link rel="manifest" href="manifest.json">\n', '')
html = html.replace('</head>', '<link rel="stylesheet" href="variants.css?v=1">\n</head>')
import re
html = re.sub(r'<script src="app.js\?[^\"]+"></script>', '<script src="variants.js?v=1"></script>\n<script src="demo-app.js?v=1"></script>', html)
(here / 'game.html').write_text(html)
