// Generated by scripts/generate_puzzles.py from reviewed word families.
// Bonus vocabulary is CC BY-SA 4.0; attribution and terms: data/DICTIONARY.md.
export const PACK_VERSION = 1;
export const PUZZLES = [
  {
    "id": "garden-001",
    "title": "Fresh Clover",
    "difficulty": "gentle",
    "letters": "SCARE",
    "rows": 5,
    "cols": 6,
    "words": [
      {
        "word": "CARE",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "CARES",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "ACRE",
        "row": 1,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "RACE",
        "row": 2,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "SCARE",
        "row": 4,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ACE",
      "ACES",
      "ACRES",
      "ARC",
      "ARCS",
      "ARE",
      "CAR",
      "CARS",
      "CASE",
      "EAR",
      "EARS",
      "ERA",
      "ERAS",
      "RACES",
      "SAC",
      "SCAR",
      "SEA"
    ]
  },
  {
    "id": "garden-002",
    "title": "Heartwood",
    "difficulty": "gentle",
    "letters": "HEART",
    "rows": 5,
    "cols": 6,
    "words": [
      {
        "word": "HARE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "HEART",
        "row": 1,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "HEAT",
        "row": 1,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "TEAR",
        "row": 1,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "HATE",
        "row": 3,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARE",
      "ART",
      "ATE",
      "EAR",
      "EARTH",
      "EAT",
      "ERA",
      "HART",
      "HAT",
      "HATER",
      "HEAR",
      "HER",
      "RAH",
      "RAT",
      "RATE",
      "RHEA",
      "TAR",
      "TEA",
      "THE"
    ]
  },
  {
    "id": "garden-003",
    "title": "Seaside",
    "difficulty": "gentle",
    "letters": "SHORE",
    "rows": 6,
    "cols": 5,
    "words": [
      {
        "word": "HERS",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "SHOE",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "ROSE",
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "SORE",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "SHORE",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "HERO",
        "row": 5,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "HER",
      "HOE",
      "HORSE",
      "HOSE",
      "ORE",
      "ROE",
      "SHE"
    ]
  },
  {
    "id": "garden-004",
    "title": "Sunny Path",
    "difficulty": "gentle",
    "letters": "SMILE",
    "rows": 6,
    "cols": 5,
    "words": [
      {
        "word": "SLIM",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "MILE",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "ISLE",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "LIME",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "SMILE",
        "row": 3,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ELM",
      "ISM",
      "LEI",
      "LIE",
      "LIES",
      "LIMES",
      "MILES",
      "SEMI",
      "SIM",
      "SLIME"
    ]
  },
  {
    "id": "garden-005",
    "title": "Stepping Stones",
    "difficulty": "gentle",
    "letters": "STONE",
    "rows": 6,
    "cols": 5,
    "words": [
      {
        "word": "NEST",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "NOTE",
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "STONE",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "NOSE",
        "row": 2,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "TONES",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "NET",
      "NETS",
      "NOT",
      "NOTES",
      "ONE",
      "ONES",
      "ONSET",
      "SENT",
      "SET",
      "SON",
      "TEN",
      "TENS",
      "TOE",
      "TOES",
      "TON",
      "TONE",
      "TONS"
    ]
  },
  {
    "id": "garden-006",
    "title": "Lemon Grove",
    "difficulty": "gentle",
    "letters": "LEMON",
    "rows": 5,
    "cols": 6,
    "words": [
      {
        "word": "MELON",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "MOLE",
        "row": 0,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "LONE",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "LEMON",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "NOEL",
        "row": 4,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ELM",
      "EMO",
      "MEN",
      "OLE",
      "OMEN",
      "ONE"
    ]
  },
  {
    "id": "garden-007",
    "title": "Morning Bread",
    "difficulty": "gentle",
    "letters": "BREAD",
    "rows": 5,
    "cols": 6,
    "words": [
      {
        "word": "BEAR",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "BREAD",
        "row": 1,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "BRED",
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "DEAR",
        "row": 1,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "READ",
        "row": 3,
        "col": 2,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARE",
      "BAD",
      "BAR",
      "BARD",
      "BARE",
      "BARED",
      "BEAD",
      "BEARD",
      "BED",
      "BRA",
      "BRAD",
      "DAB",
      "DARE",
      "DRAB",
      "EAR",
      "ERA",
      "RAD",
      "RED"
    ]
  },
  {
    "id": "garden-008",
    "title": "Open Field",
    "difficulty": "gentle",
    "letters": "FIELD",
    "rows": 6,
    "cols": 5,
    "words": [
      {
        "word": "LIFE",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "FILE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "FIELD",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "IDLE",
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "DELI",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "DEF",
      "DIE",
      "ELF",
      "FED",
      "FILED",
      "FLED",
      "LED",
      "LEI",
      "LID",
      "LIE",
      "LIED"
    ]
  },
  {
    "id": "garden-009",
    "title": "Watering Can",
    "difficulty": "gentle",
    "letters": "WATER",
    "rows": 4,
    "cols": 6,
    "words": [
      {
        "word": "WATER",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "WARE",
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "TEAR",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "RATE",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "WEAR",
        "row": 3,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARE",
      "ART",
      "ATE",
      "AWE",
      "EAR",
      "EAT",
      "ERA",
      "RAT",
      "RAW",
      "TAR",
      "TEA",
      "WAR",
      "WART",
      "WET"
    ]
  },
  {
    "id": "garden-010",
    "title": "Daydream",
    "difficulty": "gentle",
    "letters": "DREAM",
    "rows": 6,
    "cols": 5,
    "words": [
      {
        "word": "DEAR",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "REAM",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "DREAM",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "READ",
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "DAME",
        "row": 5,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARE",
      "ARM",
      "ARMED",
      "DAM",
      "DARE",
      "EAR",
      "ERA",
      "MAD",
      "MADE",
      "MAR",
      "MARE",
      "MEAD",
      "RAD",
      "RAM",
      "RED"
    ]
  },
  {
    "id": "garden-011",
    "title": "Garden Chair",
    "difficulty": "gentle",
    "letters": "CHAIR",
    "rows": 5,
    "cols": 6,
    "words": [
      {
        "word": "HAIR",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "ARCH",
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "CHAR",
        "row": 1,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "CHAI",
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "CHAIR",
        "row": 3,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "AIR",
      "ARC",
      "CAR",
      "CHI",
      "CHIA",
      "RAH",
      "RICH"
    ]
  },
  {
    "id": "garden-012",
    "title": "Clear Skies",
    "difficulty": "gentle",
    "letters": "CLEAN",
    "rows": 6,
    "cols": 5,
    "words": [
      {
        "word": "CANE",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "LEAN",
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "CLEAN",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "CLAN",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "ACNE",
        "row": 4,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ACE",
      "ALE",
      "CAN",
      "LACE",
      "LANCE",
      "LANE",
      "LEA"
    ]
  },
  {
    "id": "garden-013",
    "title": "Little Planet",
    "difficulty": "steady",
    "letters": "PLANET",
    "rows": 7,
    "cols": 6,
    "words": [
      {
        "word": "LATE",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "LEAP",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "PLATE",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "PANEL",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "PLANET",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "PLANE",
        "row": 6,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "ALE",
      "ALP",
      "ALT",
      "ANT",
      "ANTE",
      "APE",
      "APT",
      "ATE",
      "EAT",
      "LANE",
      "LAP",
      "LEA",
      "LEAN",
      "LEAPT",
      "LENT",
      "LET",
      "NAP",
      "NEAT",
      "NET",
      "PAL",
      "PALE",
      "PAN",
      "PANE",
      "PANT",
      "PAT",
      "PEA",
      "PEAT",
      "PEN",
      "PENAL",
      "PET",
      "PETAL",
      "PLAN",
      "PLANT",
      "PLAT",
      "PLEA",
      "TALE",
      "TAN",
      "TAP",
      "TAPE",
      "TEA",
      "TEAL",
      "TEN"
    ]
  },
  {
    "id": "garden-014",
    "title": "The Garden",
    "difficulty": "steady",
    "letters": "GARDEN",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "RANGE",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "READ",
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "GARDEN",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "DEAR",
        "row": 2,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "NEAR",
        "row": 2,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "GEAR",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "AGE",
      "AGED",
      "AND",
      "ANGER",
      "ARE",
      "DANG",
      "DANGER",
      "DARE",
      "DARN",
      "DEAN",
      "DEN",
      "DRAG",
      "EAR",
      "EARN",
      "END",
      "ERA",
      "GRAD",
      "GRADE",
      "GRAN",
      "GRAND",
      "NAG",
      "NERD",
      "RAD",
      "RAG",
      "RAGE",
      "RAGED",
      "RAN",
      "RAND",
      "RANG",
      "RANGED",
      "RED",
      "REND"
    ]
  },
  {
    "id": "garden-015",
    "title": "By the Stream",
    "difficulty": "steady",
    "letters": "STREAM",
    "rows": 7,
    "cols": 6,
    "words": [
      {
        "word": "SEAT",
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "TEARS",
        "row": 1,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "STARE",
        "row": 1,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "STREAM",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "SAME",
        "row": 3,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "MASTER",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARE",
      "ARM",
      "ARMS",
      "ART",
      "ARTS",
      "ATE",
      "EAR",
      "EARS",
      "EAST",
      "EAT",
      "EATS",
      "ERA",
      "ERAS",
      "MAR",
      "MARE",
      "MARS",
      "MART",
      "MAST",
      "MAT",
      "MATE",
      "MATES",
      "MATS",
      "MEAT",
      "MEATS",
      "MESA",
      "MET",
      "META",
      "RAM",
      "RAMS",
      "RAT",
      "RATE",
      "RATES",
      "RATS",
      "REAM",
      "REST",
      "SAT",
      "SEA",
      "SEAM",
      "SET",
      "SMART",
      "SMEAR",
      "STAR",
      "STEAM",
      "STEM",
      "TAME",
      "TAR",
      "TARS",
      "TEA",
      "TEAM",
      "TEAMS",
      "TEAR",
      "TEAS",
      "TERM",
      "TERMS",
      "TRAM",
      "TRAMS"
    ]
  },
  {
    "id": "garden-016",
    "title": "Wildflower",
    "difficulty": "steady",
    "letters": "FLOWER",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "WOLF",
        "row": 0,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "FORE",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "FLOWER",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "FOWL",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "WORE",
        "row": 2,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "LOWER",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ELF",
      "FEW",
      "FLEW",
      "FLOW",
      "FOE",
      "FOR",
      "FRO",
      "LORE",
      "LOW",
      "OLE",
      "ORE",
      "OWE",
      "OWL",
      "REF",
      "ROE",
      "ROLE",
      "ROW",
      "WOE"
    ]
  },
  {
    "id": "garden-017",
    "title": "Old Friends",
    "difficulty": "steady",
    "letters": "FRIEND",
    "rows": 7,
    "cols": 6,
    "words": [
      {
        "word": "FIRE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "FIND",
        "row": 1,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "FRIEND",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "FINE",
        "row": 3,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "DINE",
        "row": 3,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "RIDE",
        "row": 6,
        "col": 2,
        "direction": "across"
      }
    ],
    "bonus": [
      "DEF",
      "DEN",
      "DIE",
      "DIN",
      "DINER",
      "DIRE",
      "END",
      "FED",
      "FEND",
      "FERN",
      "FIEND",
      "FIN",
      "FINDER",
      "FINED",
      "FINER",
      "FIR",
      "FIRED",
      "FRIED",
      "INFER",
      "IRE",
      "NERD",
      "RED",
      "REF",
      "REIN",
      "REND",
      "RID",
      "RIFE",
      "RIND"
    ]
  },
  {
    "id": "garden-018",
    "title": "Market Day",
    "difficulty": "steady",
    "letters": "MARKET",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "MATE",
        "row": 0,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "MAKER",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "TAKE",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "TAME",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "RATE",
        "row": 2,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "MARKET",
        "row": 4,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARE",
      "ARK",
      "ARM",
      "ART",
      "ATE",
      "EAR",
      "EAT",
      "ERA",
      "MAKE",
      "MAR",
      "MARE",
      "MARK",
      "MART",
      "MAT",
      "MEAT",
      "MET",
      "META",
      "RAKE",
      "RAM",
      "RAT",
      "REAM",
      "TAKER",
      "TAR",
      "TEA",
      "TEAM",
      "TEAR",
      "TERM",
      "TRAM",
      "TREK"
    ]
  },
  {
    "id": "garden-019",
    "title": "Candlelight",
    "difficulty": "steady",
    "letters": "CANDLE",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "LEAD",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "CANED",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "LACE",
        "row": 1,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "LACED",
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "CANDLE",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "DANCE",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ACE",
      "ACNE",
      "ALE",
      "AND",
      "CAD",
      "CAN",
      "CANE",
      "CLAD",
      "CLAN",
      "CLEAN",
      "DALE",
      "DEAL",
      "DEAN",
      "DECAL",
      "DEN",
      "END",
      "LAD",
      "LADEN",
      "LANCE",
      "LAND",
      "LANE",
      "LEA",
      "LEAN",
      "LED",
      "LEND"
    ]
  },
  {
    "id": "garden-020",
    "title": "Orange Blossoms",
    "difficulty": "steady",
    "letters": "ORANGE",
    "rows": 5,
    "cols": 7,
    "words": [
      {
        "word": "GEAR",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "GROAN",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "RANGE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "NEAR",
        "row": 1,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "ORANGE",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "EARN",
        "row": 4,
        "col": 3,
        "direction": "across"
      }
    ],
    "bonus": [
      "AGE",
      "AGO",
      "ANGER",
      "ARE",
      "EAR",
      "EGO",
      "ERA",
      "GONE",
      "GORE",
      "GRAN",
      "NAG",
      "NOR",
      "OGRE",
      "ONE",
      "ORE",
      "ORGAN",
      "RAG",
      "RAGE",
      "RAN",
      "RANG",
      "ROE"
    ]
  },
  {
    "id": "garden-021",
    "title": "Winter Light",
    "difficulty": "steady",
    "letters": "WINTER",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "WINE",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "NEWT",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "WIRE",
        "row": 1,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "TIER",
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "WINTER",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "RENT",
        "row": 5,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "INERT",
      "INTER",
      "IRE",
      "NET",
      "NEW",
      "NIT",
      "REIN",
      "RITE",
      "TEN",
      "TIE",
      "TIN",
      "TIRE",
      "TWIN",
      "TWINE",
      "WEIR",
      "WENT",
      "WET",
      "WIN",
      "WIT",
      "WREN",
      "WRIT",
      "WRITE"
    ]
  },
  {
    "id": "garden-022",
    "title": "Pocket Seeds",
    "difficulty": "steady",
    "letters": "POCKET",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "POCKET",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "POET",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "COPE",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "PECK",
        "row": 2,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "COKE",
        "row": 2,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "POKE",
        "row": 5,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "COP",
      "COT",
      "KEPT",
      "KETO",
      "OPT",
      "PET",
      "POT",
      "TOE",
      "TOP"
    ]
  },
  {
    "id": "garden-023",
    "title": "Tree Branch",
    "difficulty": "steady",
    "letters": "BRANCH",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "CHAR",
        "row": 0,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "RANCH",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "CRAB",
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "BARN",
        "row": 2,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "BRAN",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "BRANCH",
        "row": 4,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ARC",
      "ARCH",
      "BAH",
      "BAN",
      "BAR",
      "BRA",
      "CAB",
      "CAN",
      "CAR",
      "CARB",
      "NAB",
      "NAH",
      "RAH",
      "RAN"
    ]
  },
  {
    "id": "garden-024",
    "title": "Travel Far",
    "difficulty": "steady",
    "letters": "TRAVEL",
    "rows": 7,
    "cols": 6,
    "words": [
      {
        "word": "VEAL",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "LATER",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "RATE",
        "row": 1,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "VALET",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "TRAVEL",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "TEAR",
        "row": 6,
        "col": 2,
        "direction": "across"
      }
    ],
    "bonus": [
      "ALE",
      "ALERT",
      "ALT",
      "ALTER",
      "ARE",
      "ART",
      "ATE",
      "AVE",
      "AVERT",
      "EAR",
      "EARL",
      "EAT",
      "ERA",
      "LATE",
      "LEA",
      "LET",
      "RAT",
      "RAVE",
      "REAL",
      "REV",
      "TALE",
      "TAR",
      "TEA",
      "TEAL",
      "VAL",
      "VALE",
      "VAT",
      "VET"
    ]
  },
  {
    "id": "garden-025",
    "title": "Silent Meadow",
    "difficulty": "challenge",
    "letters": "SILENT",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "INLETS",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "TILE",
        "row": 0,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "TINSEL",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "LISTEN",
        "row": 0,
        "col": 4,
        "direction": "down"
      },
      {
        "word": "NEST",
        "row": 2,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "SILENT",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ENLIST",
      "INLET",
      "INS",
      "INTEL",
      "ISLE",
      "ITS",
      "LEI",
      "LENS",
      "LENT",
      "LET",
      "LETS",
      "LIE",
      "LIEN",
      "LIES",
      "LINE",
      "LINES",
      "LIST",
      "LIT",
      "LITE",
      "NET",
      "NETS",
      "NIL",
      "NIT",
      "SENT",
      "SET",
      "SILT",
      "SIN",
      "SINE",
      "SIT",
      "SITE",
      "SLIT",
      "STEIN",
      "TEN",
      "TENS",
      "TIE",
      "TIES",
      "TIL",
      "TILES",
      "TIN",
      "TINS"
    ]
  },
  {
    "id": "garden-026",
    "title": "Rescue the Rose",
    "difficulty": "challenge",
    "letters": "RESCUE",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "CURES",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "RUSE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "SECURE",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "USER",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "SURE",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "RESCUE",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "CUE",
      "CUES",
      "CURE",
      "CURSE",
      "ERE",
      "REUSE",
      "RUE",
      "SEE",
      "SEER",
      "SUE",
      "USE"
    ]
  },
  {
    "id": "garden-027",
    "title": "Dinner Table",
    "difficulty": "challenge",
    "letters": "DINNER",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "RIDE",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "DINE",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "DINER",
        "row": 1,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "RIND",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "REND",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "DINNER",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "DEN",
      "DIE",
      "DIN",
      "DIRE",
      "END",
      "INN",
      "INNER",
      "IRE",
      "NERD",
      "NINE",
      "RED",
      "REIN",
      "RID"
    ]
  },
  {
    "id": "garden-028",
    "title": "The Artist",
    "difficulty": "challenge",
    "letters": "ARTIST",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "STAIR",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "TARS",
        "row": 0,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "SITAR",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "ARTIST",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "TART",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "STAR",
        "row": 5,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "AIR",
      "AIRS",
      "ART",
      "ARTS",
      "ITS",
      "RAT",
      "RATS",
      "SARI",
      "SAT",
      "SIR",
      "SIT",
      "START",
      "STAT",
      "STIR",
      "STRAIT",
      "TAR",
      "TAT",
      "TRAIT",
      "TRAITS"
    ]
  },
  {
    "id": "garden-029",
    "title": "Pearls of Dew",
    "difficulty": "challenge",
    "letters": "PEARLS",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "LEAP",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "PEAS",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "SALE",
        "row": 1,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "SPARE",
        "row": 1,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "PEARLS",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "REAL",
        "row": 5,
        "col": 1,
        "direction": "across"
      }
    ],
    "bonus": [
      "ALE",
      "ALP",
      "ALPS",
      "APE",
      "APES",
      "ARE",
      "ASP",
      "EAR",
      "EARL",
      "EARS",
      "ERA",
      "ERAS",
      "ESP",
      "LAP",
      "LAPS",
      "LAPSE",
      "LASER",
      "LEA",
      "LEAPS",
      "PAL",
      "PALE",
      "PALER",
      "PALS",
      "PAR",
      "PARSE",
      "PEA",
      "PEAR",
      "PEARL",
      "PEARS",
      "PER",
      "PLEA",
      "PLEAS",
      "RAP",
      "RAPS",
      "REAP",
      "REP",
      "REPS",
      "SAP",
      "SEA",
      "SEAL",
      "SLAP",
      "SPA",
      "SPAR",
      "SPEAR"
    ]
  },
  {
    "id": "garden-030",
    "title": "Songbird",
    "difficulty": "challenge",
    "letters": "SINGER",
    "rows": 7,
    "cols": 6,
    "words": [
      {
        "word": "SINGE",
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "REIGN",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "SING",
        "row": 1,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "RING",
        "row": 3,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "RESIGN",
        "row": 4,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "SINGER",
        "row": 6,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "GIN",
      "GRIN",
      "INS",
      "IRE",
      "REIGNS",
      "REIN",
      "REINS",
      "RESIN",
      "RIG",
      "RIGS",
      "RINGS",
      "RINSE",
      "RISE",
      "RISEN",
      "SIGN",
      "SIGNER",
      "SIN",
      "SINE",
      "SIR",
      "SIRE",
      "SIREN"
    ]
  },
  {
    "id": "garden-031",
    "title": "Garden Player",
    "difficulty": "challenge",
    "letters": "PLAYER",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "EARLY",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "REAL",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "PRAY",
        "row": 1,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "PLAYER",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "PEAR",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "RELAY",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ALE",
      "ALP",
      "APE",
      "ARE",
      "AYE",
      "EAR",
      "EARL",
      "ERA",
      "LAP",
      "LAY",
      "LAYER",
      "LEA",
      "LEAP",
      "PAL",
      "PALE",
      "PALER",
      "PAR",
      "PAY",
      "PAYER",
      "PEA",
      "PEARL",
      "PER",
      "PLAY",
      "PLEA",
      "PLY",
      "PREY",
      "PRY",
      "RAP",
      "RAY",
      "REAP",
      "RELY",
      "REP",
      "REPAY",
      "REPLAY",
      "REPLY",
      "RYE",
      "YEA",
      "YEAR",
      "YELP",
      "YEP"
    ]
  },
  {
    "id": "garden-032",
    "title": "Garden Gloves",
    "difficulty": "challenge",
    "letters": "GLOVES",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "LOVES",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "VOLE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "SLOG",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "GOES",
        "row": 2,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "LOSE",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "GLOVES",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "EGO",
      "EGOS",
      "GEL",
      "GLOVE",
      "LEG",
      "LEGS",
      "LOG",
      "LOGS",
      "LOVE",
      "OLE",
      "SOL",
      "SOLE",
      "SOLVE"
    ]
  },
  {
    "id": "garden-033",
    "title": "The Anchor",
    "difficulty": "challenge",
    "letters": "ANCHOR",
    "rows": 7,
    "cols": 6,
    "words": [
      {
        "word": "ARCH",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "RANCH",
        "row": 0,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "ANCHOR",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "HORN",
        "row": 2,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "ROACH",
        "row": 2,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "CHAR",
        "row": 4,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ACORN",
      "ARC",
      "CAN",
      "CAR",
      "CON",
      "CORN",
      "NACHO",
      "NAH",
      "NOR",
      "ORC",
      "RAH",
      "RAN"
    ]
  },
  {
    "id": "garden-034",
    "title": "Marble Path",
    "difficulty": "challenge",
    "letters": "MARBLE",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "MARE",
        "row": 0,
        "col": 1,
        "direction": "across"
      },
      {
        "word": "ABLE",
        "row": 0,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "AMBLE",
        "row": 1,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "BALM",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "BEAM",
        "row": 2,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "MARBLE",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "ALE",
      "AMBER",
      "ARE",
      "ARM",
      "BALE",
      "BAR",
      "BARE",
      "BEAR",
      "BLAME",
      "BRA",
      "EAR",
      "EARL",
      "ELM",
      "ERA",
      "LAB",
      "LAM",
      "LAMB",
      "LAME",
      "LEA",
      "MALE",
      "MAR",
      "MEAL",
      "RAM",
      "REAL",
      "REALM",
      "REAM"
    ]
  },
  {
    "id": "garden-035",
    "title": "Forest Walk",
    "difficulty": "challenge",
    "letters": "FOREST",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "SORE",
        "row": 0,
        "col": 3,
        "direction": "down"
      },
      {
        "word": "REST",
        "row": 0,
        "col": 5,
        "direction": "down"
      },
      {
        "word": "ROSE",
        "row": 1,
        "col": 2,
        "direction": "across"
      },
      {
        "word": "FORT",
        "row": 2,
        "col": 1,
        "direction": "down"
      },
      {
        "word": "FOREST",
        "row": 3,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "STORE",
        "row": 5,
        "col": 0,
        "direction": "across"
      }
    ],
    "bonus": [
      "FEST",
      "FOE",
      "FOES",
      "FOR",
      "FORE",
      "FORTE",
      "FORTS",
      "FOSTER",
      "FRET",
      "FRO",
      "FROST",
      "OFT",
      "ORE",
      "REF",
      "REFS",
      "ROE",
      "ROT",
      "SET",
      "SOFT",
      "SOFTER",
      "SORT",
      "TOE",
      "TOES",
      "TOR",
      "TORE"
    ]
  },
  {
    "id": "garden-036",
    "title": "Wild Orchid",
    "difficulty": "challenge",
    "letters": "ORCHID",
    "rows": 6,
    "cols": 6,
    "words": [
      {
        "word": "CHOIR",
        "row": 0,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "CHORD",
        "row": 0,
        "col": 0,
        "direction": "down"
      },
      {
        "word": "ORCHID",
        "row": 2,
        "col": 0,
        "direction": "across"
      },
      {
        "word": "CORD",
        "row": 2,
        "col": 2,
        "direction": "down"
      },
      {
        "word": "RICH",
        "row": 4,
        "col": 2,
        "direction": "across"
      }
    ],
    "bonus": [
      "CHI",
      "COD",
      "DOC",
      "HID",
      "ORC",
      "RID",
      "ROD"
    ]
  }
];
